/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package assignment;

import javax.swing.JOptionPane;

/**
 * This class creates the manager page were a manager can alter Different tables
 * within the databased.
 *
 *
 * @date 02/05/2018
 * @author mjwat
 */
public class FrameManager extends javax.swing.JFrame {

    /**
     * Creates new form FrameManager
     */
    private DatabaseConnection databaseConnection;
    private int currentIndex;
    private int numberOfRecords;

    public FrameManager() {
        initComponents();
        setLocationRelativeTo(null);
        databaseConnection = new DatabaseConnection();
        jPanel2.setVisible(false);
    }//FrameManager

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblManagerScreenTitle = new javax.swing.JLabel();
        btnHome = new javax.swing.JButton();
        Items = new javax.swing.JButton();
        btnViewChangeStaff = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblItemTitle = new javax.swing.JLabel();
        lblItemName = new javax.swing.JLabel();
        txtItemName = new javax.swing.JTextField();
        lblStock = new javax.swing.JLabel();
        txtItemStock = new javax.swing.JTextField();
        lblPrice = new javax.swing.JLabel();
        txtItemPrice = new javax.swing.JTextField();
        btnAddNewItem = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblBuilderFirstName = new javax.swing.JLabel();
        txtBuilderFirstName = new javax.swing.JTextField();
        txtBuilderSecondName = new javax.swing.JTextField();
        lblBuilderSecondName = new javax.swing.JLabel();
        txtBuilderManagerID = new javax.swing.JTextField();
        lblBuilderManager = new javax.swing.JLabel();
        txtBuilderPassword = new javax.swing.JTextField();
        lblBuilderPassword = new javax.swing.JLabel();
        lblNewItem = new javax.swing.JLabel();
        btnAddBuilder = new javax.swing.JButton();
        lblBuilderJobRole = new javax.swing.JLabel();
        lblBuilderLoginName = new javax.swing.JLabel();
        txtBuilderJobRole = new javax.swing.JTextField();
        txtBuilderLoginName = new javax.swing.JTextField();
        btnAddCourier = new javax.swing.JButton();
        txtCourierLoginName = new javax.swing.JTextField();
        txtCourierPassword = new javax.swing.JTextField();
        txtCourierManagerID = new javax.swing.JTextField();
        txtCourierSecondName = new javax.swing.JTextField();
        txtCourierFirstName = new javax.swing.JTextField();
        lblCourierFirstName = new javax.swing.JLabel();
        lblTitleCourier = new javax.swing.JLabel();
        lblCourierSecondName = new javax.swing.JLabel();
        lblCourierManagerID = new javax.swing.JLabel();
        lblCourierPassword = new javax.swing.JLabel();
        lblCourierLoginName = new javax.swing.JLabel();
        lblBackground = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 500));
        setResizable(false);
        setSize(new java.awt.Dimension(800, 500));
        getContentPane().setLayout(null);

        lblManagerScreenTitle.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblManagerScreenTitle.setText("Manager Screen");
        getContentPane().add(lblManagerScreenTitle);
        lblManagerScreenTitle.setBounds(330, 40, 150, 24);
        lblManagerScreenTitle.getAccessibleContext().setAccessibleName("lblTitle");

        btnHome.setText("Home");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        getContentPane().add(btnHome);
        btnHome.setBounds(680, 10, 90, 32);

        Items.setText("Items");
        Items.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemsActionPerformed(evt);
            }
        });
        getContentPane().add(Items);
        Items.setBounds(140, 40, 110, 32);

        btnViewChangeStaff.setText("Staff");
        btnViewChangeStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewChangeStaffActionPerformed(evt);
            }
        });
        getContentPane().add(btnViewChangeStaff);
        btnViewChangeStaff.setBounds(20, 40, 110, 32);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        lblItemTitle.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblItemTitle.setText("New Item");

        lblItemName.setText("Item Name");

        lblStock.setText("Stock");

        lblPrice.setText("Price £");

        btnAddNewItem.setText("Add Item");
        btnAddNewItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewItemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAddNewItem, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(lblItemTitle))
                            .addComponent(lblPrice, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblStock, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblItemName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtItemName, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                            .addComponent(txtItemStock)
                            .addComponent(txtItemPrice))))
                .addContainerGap(9, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblItemTitle)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblItemName)
                    .addComponent(txtItemName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStock)
                    .addComponent(txtItemStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrice)
                    .addComponent(txtItemPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAddNewItem)
                .addContainerGap(103, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(20, 80, 340, 280);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        lblBuilderFirstName.setText("First Name");

        lblBuilderSecondName.setText("Second Name");

        lblBuilderManager.setText("Manager ID");

        lblBuilderPassword.setText("Password");

        lblNewItem.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblNewItem.setText("New Builder");

        btnAddBuilder.setText("Add Builder");
        btnAddBuilder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddBuilderActionPerformed(evt);
            }
        });

        lblBuilderJobRole.setText("Job Role");

        lblBuilderLoginName.setText("Login Name");

        btnAddCourier.setText("Add Courier");
        btnAddCourier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCourierActionPerformed(evt);
            }
        });

        lblCourierFirstName.setText("First Name");

        lblTitleCourier.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblTitleCourier.setText("New Courier");

        lblCourierSecondName.setText("Second Name");

        lblCourierManagerID.setText("Manager ID");

        lblCourierPassword.setText("Password");

        lblCourierLoginName.setText("Login Name");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBuilderSecondName)
                            .addComponent(lblBuilderFirstName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtBuilderSecondName, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                            .addComponent(txtBuilderFirstName)))
                    .addComponent(lblNewItem)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBuilderPassword)
                            .addComponent(lblBuilderJobRole)
                            .addComponent(lblBuilderLoginName)
                            .addComponent(lblBuilderManager))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(btnAddBuilder, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtBuilderLoginName, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtBuilderJobRole, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                                        .addComponent(txtBuilderPassword, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtBuilderManagerID)))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblTitleCourier)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblCourierManagerID)
                                .addComponent(lblCourierLoginName)
                                .addComponent(lblCourierPassword))
                            .addGap(7, 7, 7)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(125, 125, 125)
                                    .addComponent(btnAddCourier, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(23, 23, 23)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtCourierPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtCourierManagerID, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtCourierLoginName, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCourierSecondName)
                            .addComponent(lblCourierFirstName))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCourierFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCourierSecondName, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(68, 68, 68))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblNewItem)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblBuilderFirstName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblBuilderSecondName)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(lblBuilderManager)
                                            .addComponent(txtBuilderManagerID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(lblBuilderPassword)
                                            .addComponent(txtBuilderPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(lblBuilderJobRole)
                                            .addComponent(txtBuilderJobRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblBuilderLoginName)
                                            .addComponent(txtBuilderLoginName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(txtBuilderSecondName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(txtBuilderFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAddBuilder))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblTitleCourier)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(28, 28, 28)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblCourierManagerID)
                                            .addComponent(txtCourierManagerID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtCourierSecondName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblCourierSecondName))))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtCourierFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblCourierFirstName)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCourierPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCourierPassword))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCourierLoginName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCourierLoginName))
                        .addComponent(btnAddCourier)))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        lblNewItem.getAccessibleContext().setAccessibleName("lblTileBuilder");

        getContentPane().add(jPanel1);
        jPanel1.setBounds(20, 80, 750, 280);

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/shutterstock_617032220.jpg"))); // NOI18N
        lblBackground.setMaximumSize(new java.awt.Dimension(800, 500));
        lblBackground.setMinimumSize(new java.awt.Dimension(800, 500));
        lblBackground.setPreferredSize(new java.awt.Dimension(800, 500));
        getContentPane().add(lblBackground);
        lblBackground.setBounds(-3, -8, 810, 510);
        lblBackground.getAccessibleContext().setAccessibleName("lblBackground");

        lblTitle.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        lblTitle.setText("Manager Page");
        getContentPane().add(lblTitle);
        lblTitle.setBounds(320, 50, 124, 24);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Button to add new builder to the database.
     *
     * @author mjwatters
     * @Date 01/05/2018
     *
     * @param evt
     */
    private void btnAddBuilderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddBuilderActionPerformed

        boolean done = databaseConnection.insertBuilder(Integer.parseInt(txtBuilderManagerID.getText()),
                txtBuilderFirstName.getText(),
                txtBuilderSecondName.getText(),
                txtBuilderPassword.getText(),
                txtBuilderJobRole.getText(),
                txtBuilderLoginName.getText()
        );
        if (done == true) {
            JOptionPane.showMessageDialog(this, "Builder added", "Adding Record", JOptionPane.PLAIN_MESSAGE);

        } else {
            JOptionPane.showMessageDialog(this, "Order not added", "Error", JOptionPane.PLAIN_MESSAGE);
        }//eise
    }//GEN-LAST:event_btnAddBuilderActionPerformed

    /**
     * Button to add a new courier to the database
     *
     * @author mjwatters
     * @Date 01/05/2018
     * @param evt
     */
    private void btnAddCourierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCourierActionPerformed
        boolean done = databaseConnection.insertCourier(Integer.parseInt(txtCourierManagerID.getText()),
                txtCourierFirstName.getText(),
                txtCourierSecondName.getText(),
                txtCourierPassword.getText(),
                txtCourierLoginName.getText()
        );
        if (done == true) {
            JOptionPane.showMessageDialog(this, "Courier added", "Adding Record", JOptionPane.PLAIN_MESSAGE);

        } else {
            JOptionPane.showMessageDialog(this, "Courier not added", "Error", JOptionPane.PLAIN_MESSAGE);
        }//else
    }//GEN-LAST:event_btnAddCourierActionPerformed

    /**
     * This button allows the user to return to home page
     *
     * @author mjwatters
     * @Date 01/05/2018
     */
    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        this.dispose();
        HomePage homePage = new HomePage();
        homePage.setVisible(true);
    }//GEN-LAST:event_btnHomeActionPerformed

    /**
     * Button to change the visability of Panels in Manager screen
     *
     * @author mjwatters
     * @Date 01/05/2018
     * @param evt
     */

    private void btnViewChangeStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewChangeStaffActionPerformed
        jPanel2.setVisible(false);
        jPanel1.setVisible(true);

    }//GEN-LAST:event_btnViewChangeStaffActionPerformed

    /**
     * Button to change the visability of Panels in Manager screen
     *
     * @author mjwatters
     * @Date 01/05/2018
     * @param evt
     */
    private void ItemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemsActionPerformed
        jPanel1.setVisible(false);
        jPanel2.setVisible(true);
    }//GEN-LAST:event_ItemsActionPerformed

    /**
     * Button to add a new item to the database.
     *
     * @author mjwatters
     * @Date 01/05/2018
     * @param evt
     */
    private void btnAddNewItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewItemActionPerformed
        boolean done = databaseConnection.insertItem(txtItemName.getText(),
                Integer.parseInt(txtItemPrice.getText()),
                Integer.parseInt(txtItemStock.getText())
        );
        if (done == true) {
            JOptionPane.showMessageDialog(this, "Item added", "Adding Record", JOptionPane.PLAIN_MESSAGE);

        } else {
            JOptionPane.showMessageDialog(this, "Order not added", "Error", JOptionPane.PLAIN_MESSAGE);
        }
    }//GEN-LAST:event_btnAddNewItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameManager().setVisible(true);
            }
        });
    }//main

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Items;
    private javax.swing.JButton btnAddBuilder;
    private javax.swing.JButton btnAddCourier;
    private javax.swing.JButton btnAddNewItem;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnViewChangeStaff;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblBuilderFirstName;
    private javax.swing.JLabel lblBuilderJobRole;
    private javax.swing.JLabel lblBuilderLoginName;
    private javax.swing.JLabel lblBuilderManager;
    private javax.swing.JLabel lblBuilderPassword;
    private javax.swing.JLabel lblBuilderSecondName;
    private javax.swing.JLabel lblCourierFirstName;
    private javax.swing.JLabel lblCourierLoginName;
    private javax.swing.JLabel lblCourierManagerID;
    private javax.swing.JLabel lblCourierPassword;
    private javax.swing.JLabel lblCourierSecondName;
    private javax.swing.JLabel lblItemName;
    private javax.swing.JLabel lblItemTitle;
    private javax.swing.JLabel lblManagerScreenTitle;
    private javax.swing.JLabel lblNewItem;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblStock;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTitleCourier;
    private javax.swing.JTextField txtBuilderFirstName;
    private javax.swing.JTextField txtBuilderJobRole;
    private javax.swing.JTextField txtBuilderLoginName;
    private javax.swing.JTextField txtBuilderManagerID;
    private javax.swing.JTextField txtBuilderPassword;
    private javax.swing.JTextField txtBuilderSecondName;
    private javax.swing.JTextField txtCourierFirstName;
    private javax.swing.JTextField txtCourierLoginName;
    private javax.swing.JTextField txtCourierManagerID;
    private javax.swing.JTextField txtCourierPassword;
    private javax.swing.JTextField txtCourierSecondName;
    private javax.swing.JTextField txtItemName;
    private javax.swing.JTextField txtItemPrice;
    private javax.swing.JTextField txtItemStock;
    // End of variables declaration//GEN-END:variables
}
