/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package assignment;

import javax.swing.JOptionPane;

/**
 * This class create the area that is user to navigate between the varous
 * screens within the applicaiotn
 *
 * @date 02/05/2018
 * @author mjwat
 */
public class HomePage extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    public HomePage() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnManagement = new javax.swing.JButton();
        btnPlaceDelivery = new javax.swing.JButton();
        btnManageDelivery = new javax.swing.JButton();
        btnTrackDelivery = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        lblBackgroundImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 350));
        setResizable(false);
        setSize(new java.awt.Dimension(400, 350));
        getContentPane().setLayout(null);

        btnManagement.setText("Management Screen");
        btnManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManagementActionPerformed(evt);
            }
        });
        getContentPane().add(btnManagement);
        btnManagement.setBounds(100, 230, 200, 32);

        btnPlaceDelivery.setText("Place Order");
        btnPlaceDelivery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlaceDeliveryActionPerformed(evt);
            }
        });
        getContentPane().add(btnPlaceDelivery);
        btnPlaceDelivery.setBounds(100, 110, 200, 32);

        btnManageDelivery.setText("Manage Delivery");
        btnManageDelivery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageDeliveryActionPerformed(evt);
            }
        });
        getContentPane().add(btnManageDelivery);
        btnManageDelivery.setBounds(100, 150, 200, 32);

        btnTrackDelivery.setText("Track Deliverys");
        btnTrackDelivery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrackDeliveryActionPerformed(evt);
            }
        });
        getContentPane().add(btnTrackDelivery);
        btnTrackDelivery.setBounds(100, 190, 200, 32);

        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogout);
        btnLogout.setBounds(299, 10, 90, 32);

        lblBackgroundImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/img5190_PG22-Construction.jpg"))); // NOI18N
        getContentPane().add(lblBackgroundImage);
        lblBackgroundImage.setBounds(0, 0, 400, 350);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageDeliveryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageDeliveryActionPerformed
        if (Main.courier == true) {
            this.dispose();
            FrameCourier frameCourier = new FrameCourier();
            frameCourier.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "You do not have access, Courier and Manager only.", "Attendtion", JOptionPane.PLAIN_MESSAGE);
        }//else

    }//GEN-LAST:event_btnManageDeliveryActionPerformed

    private void btnPlaceDeliveryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlaceDeliveryActionPerformed
        if (Main.builder == true) {
            this.dispose();
            FrameDelivery frameDelivery = new FrameDelivery();
            frameDelivery.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "You do not have access, Builder and Manager only.", "Attendtion", JOptionPane.PLAIN_MESSAGE);
        }//else
    }//GEN-LAST:event_btnPlaceDeliveryActionPerformed

    /**
     * *
     * This button allows user to navigate to the track delivery screen
     *
     * @date 02/05/2018
     * @auther Michael Watters
     * @param evt
     */
    private void btnTrackDeliveryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrackDeliveryActionPerformed

        this.dispose();
        TrackDeliverys trackDelivery = new TrackDeliverys();
        trackDelivery.setVisible(true);
    }//GEN-LAST:event_btnTrackDeliveryActionPerformed
    /**
     * *
     * This button allows the user to logout and return the login screen.
     *
     * @date 02/05/2018
     * @author Michael Watters
     * @param evt
     */
    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        Main.builder = false;
        Main.courier = false;
        Main.manager = false;
        Main.builderID = "";
        Main.courierID = "";
        Main.managerID = "";
        this.dispose();
        FrameLogin frameLogin = new FrameLogin();
        frameLogin.setVisible(true);
    }//GEN-LAST:event_btnLogoutActionPerformed

    /**
     * *
     * This checks if the user is a manager and if they are gives them access
     * too the Management screen.
     *
     * @date 02/05/2018
     * @auhor Michael Watters
     * @param evt
     */
    private void btnManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManagementActionPerformed
        if (Main.manager == true) {
            this.dispose();
            FrameManager frameManager = new FrameManager();
            frameManager.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "You do not have access, Manager Only", "Attendtion", JOptionPane.PLAIN_MESSAGE);
        }
    }//GEN-LAST:event_btnManagementActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnManageDelivery;
    private javax.swing.JButton btnManagement;
    private javax.swing.JButton btnPlaceDelivery;
    private javax.swing.JButton btnTrackDelivery;
    private javax.swing.JLabel lblBackgroundImage;
    // End of variables declaration//GEN-END:variables
}
