/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package assignment;

import java.util.Arrays;

/**
 *
 * @author mjwat
 */
public class TrackDeliverys extends javax.swing.JFrame {

    private DatabaseConnection databaseConnection;
    private Order[] arrayOfOrders;
    private Item[] arrayOfItems;
    private Location[] arrayOfLocations;
    private int currentIndex;
    private int numberOfRecords;

    /**
     * Creates new form TrackCouriers
     */
    public TrackDeliverys() {
        initComponents();
        setLocationRelativeTo(null);
        databaseConnection = new DatabaseConnection();
        arrayOfItems = databaseConnection.getAllItemsTest();
        arrayOfLocations = databaseConnection.getAllLocations();
        for (Item arrayOfItem : arrayOfItems) {
            System.out.println(arrayOfItem.getItemName());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        btnHome = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        txtOrderID = new javax.swing.JTextField();
        txtLocation = new javax.swing.JTextField();
        txtWhen = new javax.swing.JTextField();
        txtNum1 = new javax.swing.JTextField();
        txtNum2 = new javax.swing.JTextField();
        lblOf = new javax.swing.JLabel();
        lblOrderID = new javax.swing.JLabel();
        lblLocation = new javax.swing.JLabel();
        lblWhen = new javax.swing.JLabel();
        lblBuilder = new javax.swing.JLabel();
        lblItem = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        lblNotes = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtNotes = new javax.swing.JTextPane();
        txtStatus = new javax.swing.JTextField();
        txtItem = new javax.swing.JTextField();
        txtBuilder = new javax.swing.JTextField();
        btnPreivous = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        lblBackground = new javax.swing.JLabel();

        jMenu1.setText("jMenu1");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 500));
        setResizable(false);
        getContentPane().setLayout(null);

        btnHome.setText("Home");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        getContentPane().add(btnHome);
        btnHome.setBounds(670, 10, 100, 32);

        jPanel1.setLayout(null);

        txtOrderID.setEditable(false);
        jPanel1.add(txtOrderID);
        txtOrderID.setBounds(80, 20, 160, 24);

        txtLocation.setEditable(false);
        jPanel1.add(txtLocation);
        txtLocation.setBounds(80, 50, 160, 24);

        txtWhen.setEditable(false);
        jPanel1.add(txtWhen);
        txtWhen.setBounds(80, 80, 160, 24);

        txtNum1.setEditable(false);
        jPanel1.add(txtNum1);
        txtNum1.setBounds(100, 130, 40, 24);

        txtNum2.setEditable(false);
        jPanel1.add(txtNum2);
        txtNum2.setBounds(180, 130, 40, 24);

        lblOf.setText("of");
        jPanel1.add(lblOf);
        lblOf.setBounds(150, 140, 20, 16);

        lblOrderID.setText("OrderID");
        jPanel1.add(lblOrderID);
        lblOrderID.setBounds(30, 20, 70, 20);

        lblLocation.setText("Location");
        jPanel1.add(lblLocation);
        lblLocation.setBounds(20, 50, 70, 20);

        lblWhen.setText("When");
        jPanel1.add(lblWhen);
        lblWhen.setBounds(30, 80, 60, 20);

        lblBuilder.setText("Builder");
        jPanel1.add(lblBuilder);
        lblBuilder.setBounds(280, 20, 40, 20);

        lblItem.setText("Item");
        jPanel1.add(lblItem);
        lblItem.setBounds(290, 50, 40, 20);

        lblStatus.setText("Status");
        jPanel1.add(lblStatus);
        lblStatus.setBounds(280, 80, 37, 20);

        lblNotes.setText("Notes");
        jPanel1.add(lblNotes);
        lblNotes.setBounds(280, 120, 33, 16);

        txtNotes.setEditable(false);
        jScrollPane1.setViewportView(txtNotes);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(320, 120, 210, 80);

        txtStatus.setEditable(false);
        jPanel1.add(txtStatus);
        txtStatus.setBounds(320, 80, 210, 24);

        txtItem.setEditable(false);
        jPanel1.add(txtItem);
        txtItem.setBounds(320, 50, 210, 24);

        txtBuilder.setEditable(false);
        jPanel1.add(txtBuilder);
        txtBuilder.setBounds(320, 20, 210, 24);

        btnPreivous.setText("Preivous");
        btnPreivous.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreivousActionPerformed(evt);
            }
        });
        jPanel1.add(btnPreivous);
        btnPreivous.setBounds(30, 170, 110, 32);

        btnNext.setText("Next");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });
        jPanel1.add(btnNext);
        btnNext.setBounds(170, 170, 110, 32);

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        jPanel1.add(btnRefresh);
        btnRefresh.setBounds(320, 200, 210, 32);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(100, 80, 580, 250);

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel10.setText("Track All Orders");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(310, 20, 150, 24);

        lblBackground.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        lblBackground.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/shutterstock_617032220.jpg"))); // NOI18N
        lblBackground.setToolTipText("");
        getContentPane().add(lblBackground);
        lblBackground.setBounds(0, 0, 801, 508);

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
     * Returns the user to the home page
     *
     * @author Michael Watters
     * @date 02/05/2018
     * @param evt
     */
    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        this.dispose();
        HomePage homePage = new HomePage();
        homePage.setVisible(true);
    }//GEN-LAST:event_btnHomeActionPerformed

    /**
     * Navigates to the previous record in the database
     *
     * @author Michael Watters
     * @date 02/05/2018
     * @param evt
     */
    private void btnPreivousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreivousActionPerformed
        if (currentIndex != 0) {
            currentIndex--;
            txtNum1.setText(Integer.toString(currentIndex + 1));
            //display the first students details                 
            String idText = Integer.toString(arrayOfOrders[currentIndex].getOrderID());
            txtOrderID.setText(idText);
            System.out.println("Set Order ID");
            txtWhen.setText(arrayOfOrders[currentIndex].getDateRequired());
            System.out.println("Set date");
            txtNotes.setText(arrayOfOrders[currentIndex].getNotes());
            System.out.println("Set Notes");
            txtStatus.setText((arrayOfOrders[currentIndex].getStatus()));
            System.out.println("Set Status");

            //Broken down due to compile errors with netbeans
            int tempItemID = (arrayOfOrders[currentIndex].getItemID());
            int tempBuilderID = (arrayOfOrders[currentIndex].getBuilderID());
            int tempLocationID = (arrayOfOrders[currentIndex].getLocationID());

            String tempItemIDString = arrayOfItems[tempItemID - 1].getItemName();
            String tempBuilderIDString = Integer.toString(tempBuilderID);
            String tempLocationIDString = arrayOfLocations[tempLocationID - 1].getLocationName();

            txtItem.setText(tempItemIDString);
            System.out.println("Set item ID");
            txtBuilder.setText(tempBuilderIDString);
            System.out.println("Set Builder ID");
            txtLocation.setText(tempLocationIDString);
            System.out.println("Set Location");
        }
    }//GEN-LAST:event_btnPreivousActionPerformed

    /**
     * Navigates to the Next record in the database
     *
     * @author Michael Watters
     * @date 02/05/2018
     * @param evt
     */
    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        numberOfRecords = databaseConnection.numRecordsInQuery;
        //button will move to the record after current one         
        //if the last record is showing there will be no response         
        if (currentIndex < numberOfRecords - 1) {
            currentIndex++;
            txtNum1.setText(Integer.toString(currentIndex + 1));
            //display the students details at currentIndex             
            String idText = Integer.toString(arrayOfOrders[currentIndex].getOrderID());
            txtOrderID.setText(idText);
            System.out.println("Set Order ID");
            txtWhen.setText(arrayOfOrders[currentIndex].getDateRequired());
            System.out.println("Set date");
            txtNotes.setText(arrayOfOrders[currentIndex].getNotes());
            System.out.println("Set Notes");
            txtStatus.setText((arrayOfOrders[currentIndex].getStatus()));
            System.out.println("Set Status");

            //Broken down due to compile errors with netbeans
            int tempItemID = (arrayOfOrders[currentIndex].getItemID());
            int tempBuilderID = (arrayOfOrders[currentIndex].getBuilderID());
            int tempLocationID = (arrayOfOrders[currentIndex].getLocationID());

            String tempItemIDString = arrayOfItems[tempItemID - 1].getItemName();
            String tempBuilderIDString = Integer.toString(tempBuilderID);
            String tempLocationIDString = arrayOfLocations[tempLocationID - 1].getLocationName();

            txtItem.setText(tempItemIDString);
            System.out.println("Set item ID");
            txtBuilder.setText(tempBuilderIDString);
            System.out.println("Set Builder ID");
            txtLocation.setText(tempLocationIDString);
            System.out.println("Set Location");
        }
    }//GEN-LAST:event_btnNextActionPerformed

    /**
     * Gets all the records within the database.
     *
     * @author Michael Watters
     * @date 02/05/2018
     * @param evt
     */
    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        try {

            //set up array to store the data sent back from the DatabaseConnection             
            arrayOfOrders = databaseConnection.getAllOrdersAllStatus();
            //number of items in the array             
            numberOfRecords = databaseConnection.numRecordsInQuery;
            currentIndex = 0;
            if (numberOfRecords != 0) {

                //display the first students details                 
                String idText = Integer.toString(arrayOfOrders[currentIndex].getOrderID());
                txtOrderID.setText(idText);
                System.out.println("Set Order ID");
                txtWhen.setText(arrayOfOrders[currentIndex].getDateRequired());
                System.out.println("Set date");
                txtNotes.setText(arrayOfOrders[currentIndex].getNotes());
                System.out.println("Set Notes");
                txtStatus.setText((arrayOfOrders[currentIndex].getStatus()));
                System.out.println("Set Status");

                //Broken down due to compile errors with netbeans
                int tempItemID = (arrayOfOrders[currentIndex].getItemID());
                int tempBuilderID = (arrayOfOrders[currentIndex].getBuilderID());
                int tempLocationID = (arrayOfOrders[currentIndex].getLocationID());

                String tempItemIDString = arrayOfItems[tempItemID - 1].getItemName();
                String tempBuilderIDString = Integer.toString(tempBuilderID);
                String tempLocationIDString = arrayOfLocations[tempLocationID - 1].getLocationName();

                txtItem.setText(tempItemIDString);
                System.out.println("Set item ID");
                txtBuilder.setText(tempBuilderIDString);
                System.out.println("Set Builder ID");
                txtLocation.setText(tempLocationIDString);
                System.out.println("Set Location");

                //display the current index for current and last record                 
                txtNum1.setText(Integer.toString(currentIndex + 1));
                txtNum2.setText(Integer.toString(numberOfRecords));

                //enable buttons to navigate through students                 
                btnNext.setEnabled(true);
                btnPreivous.setEnabled(true);
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }//catch
    }//GEN-LAST:event_btnRefreshActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrackDeliverys.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrackDeliverys.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrackDeliverys.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrackDeliverys.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrackDeliverys().setVisible(true);
            }
        });
    }//main

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPreivous;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblBuilder;
    private javax.swing.JLabel lblItem;
    private javax.swing.JLabel lblLocation;
    private javax.swing.JLabel lblNotes;
    private javax.swing.JLabel lblOf;
    private javax.swing.JLabel lblOrderID;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblWhen;
    private javax.swing.JTextField txtBuilder;
    private javax.swing.JTextField txtItem;
    private javax.swing.JTextField txtLocation;
    private javax.swing.JTextPane txtNotes;
    private javax.swing.JTextField txtNum1;
    private javax.swing.JTextField txtNum2;
    private javax.swing.JTextField txtOrderID;
    private javax.swing.JTextField txtStatus;
    private javax.swing.JTextField txtWhen;
    // End of variables declaration//GEN-END:variables
}
